# Generated by Django 4.2.5 on 2023-11-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
